kellyselden/git-diff-apply

src/get-checked-out-branch-name.js
src/index.js
test/acceptance/git-diff-apply-test.js
test/unit/get-checked-out-branch-name-test.js

retain previously checked out branch

---

bin/.eslintrc.js
bin/git-diff-apply.js
src/index.js
src/is-git-clean.js
test/acceptance/git-diff-apply-test.js
test/unit/is-git-clean-test.js

add a clean git assertion

---

bin/git-diff-apply.js
src/index.js
test/acceptance/git-diff-apply-test.js

Reference https://github.com/kellyselden/ember-cli-update/issues/55
cc @rwjblue

add --ignore-conflicts option

---

package.json

chore(package): update git-fixtures to version 0.7.2

---

bin/git-diff-apply.js
src/index.js
test/acceptance/git-diff-apply-test.js
test/fixtures/local/conflict/local/present-ignored-changed.txt
test/fixtures/merge/conflict/present-ignored-changed.txt
test/fixtures/remote/conflict/v1/present-ignored-changed.txt
test/fixtures/remote/conflict/v2/present-ignored-changed.txt
test/fixtures/remote/conflict/v3/present-ignored-changed.txt

This will help https://github.com/kellyselden/ember-cli-update/pull/70
You can now ignore package.json
cc @rwjblue

add ignored-files option

---

test/Integration/index-test.js
test/acceptance/git-diff-apply-test.js
test/helpers/build-tmp.js

move some acceptance tests to integration tests

---

src/index.js
test/integration/index-test.js

Closes https://github.com/kellyselden/ember-cli-update/issues/106.

no-op when start and end tag match

---

src/copy.js
src/index.js

copy now takes explicit destination

---

.travis.yml

add osx testing

---

src/index.js
test/integration/index-test.js

gracefully handle running outside a git repository

---

bin/git-diff-apply.js
src/index.js
test/acceptance/git-diff-apply-test.js
test/integration/index-test.js

related to https://github.com/kellyselden/ember-cli-update/issues/207
cc @rwjblue

convert --ignore-conflicts to --resolve-conflicts

---

package.json

Reverts kellyselden/git-diff-apply#132

Revert "chore(deps): pin dependencies"

---

src/index.js
test/integration/index-test.js

This reverts commit e03f4f898d792b63eeda98c0d70c6bcda88b6ecc.

Revert "remove unnecessary is-git-clean export"

---

package-lock.json
package.json
test/acceptance/git-diff-apply-test.js
test/integration/index-test.js

use co in tests

---

src/index.js
test/fixtures/local/gitignored/local/.gitignore
test/fixtures/merge/gitignored/.gitignore
test/fixtures/remote/gitignored/v1/.gitignore
test/fixtures/remote/gitignored/v3/.gitignore
test/integration/index-test.js

https://github.com/ember-cli/ember-cli-update/issues/143

preserve locally gitignored

---

src/git-remove-all.js

Fixes https://github.com/ember-cli/ember-cli-update/issues/535.

don't delete cwd (because monorepo)

---

src/git-remove-all.js

Reverts kellyselden/git-diff-apply#220

Revert "don't delete cwd (because monorepo)"

---

src/index.js
test/integration/index-test.js

fix ignored file that doesn't exist

---

package.json
src/git-remove-all.js

attempt to fix https://github.com/ember-cli/ember-cli-update/issues/583

up maxBuffer on ls-files

---

package-lock.json
package.json
test/integration/index-test.js

https://github.com/kellyselden/git-diff-apply/pull/278#pullrequestreview-282336873
This should pass once #278 is merged.
cc @ejlangev

add a monorepo performance regression test

---

src/create-custom-remote.js
test/integration/index-test.js

Fixes https://github.com/ember-cli/ember-cli-update/issues/733

fix custom diff + reset + same tag

---

src/git-remove-all.js
test/integration/index-test.js

`git add -f` to bypass global gitignore

---

src/check-out-tag.js
src/index.js

not sure why this was every needed?

remove --mirror from git clone

---

src/index.js

to prevent injecting a command

spawn git clone

---

src/commit-and-tag.js
src/commit.js
src/index.js
test/integration/index-test.js

add commit message

---

src/index.js
test/integration/index-test.js

https://github.com/kellyselden/boilerplate-update/issues/202

handle missing tags gracefully

---

.travis.yml
appveyor.yml
src/git-init.js

https://github.com/ember-cli/ember-cli-update/issues/995

run tests with diff.noprefix true

---

package-lock.json
package.json
src/git-remove-all.js
src/run.js

This reverts commit b760d598aaaf5e2170a67ea460463260d06bb039.

Revert "use execa"

---

src/index.js

remove exec reexport
